# Generated by Django 6.0.6 on 2026-07-02 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LlmModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LlmAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "role",
                    models.CharField(
                        help_text="System role for the agent, e.g. 'You are a helpful assistant.'",
                        max_length=255,
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Additional system context or instructions for the agent.",
                    ),
                ),
                (
                    "use_other_agent",
                    models.BooleanField(
                        default=False,
                        help_text="Use a custom OpenAI-compatible endpoint (Ollama, Gemini, etc.).",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Required when using another agent, e.g. http://localhost:11434/v1",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API key for OpenAI or the compatible provider.",
                        max_length=512,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        limit_choices_to={"active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agents",
                        to="llm.llmmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Agent",
                "verbose_name_plural": "LLM Agents",
                "ordering": ["name"],
            },
        ),
    ]
