# Generated by Django 6.0.6 on 2026-07-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Snake_case function name, e.g. get_ticket_price",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description shown to the LLM for when to use this tool."
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="OpenAI function parameters JSON schema (type, properties, required).",
                    ),
                ),
                (
                    "python_code",
                    models.TextField(
                        help_text='Python function body. Use kwargs, e.g. city = kwargs["destination_city"]'
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("file_generated", models.BooleanField(default=False, editable=False)),
                (
                    "generated_file",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "generated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Tool",
                "verbose_name_plural": "Agent Tools",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="llmagent",
            name="tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tools this agent may call via the LLM.",
                related_name="agents",
                to="llm.agenttool",
            ),
        ),
    ]
