# Generated by Django 6.0.6 on 2026-07-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_agenttool_llmagent_tools"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vd_name", models.CharField(editable=False, max_length=255)),
                ("description", models.TextField()),
                ("result", models.TextField(blank=True)),
                ("vd_processed", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="llm.llmagent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Task",
                "verbose_name_plural": "Agent Tasks",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent", "vd_name"), name="unique_agent_task_vd_name"
                    )
                ],
            },
        ),
    ]
