# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0005_project_agenttask_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteKnowledgeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("root_url", models.URLField()),
                ("selected_urls", models.JSONField(default=list)),
                ("use_llm_cleanup", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_knowledge_jobs",
                        to="llm.llmagent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Knowledge Job",
                "verbose_name_plural": "Website Knowledge Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
